src/main/java/com/example/beepoo/controller/TestController.java
=> Jenkins 테스트

src/main/java/com/example/beepoo/exception/CustomException.java, src/main/java/com/example/beepoo/exception/ErrorCode.java
=> init: 에러 코드 기본 세팅

src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/dto/ItemDto.java, src/main/java/com/example/beepoo/entity/ItemEntity.java, src/main/java/com/example/beepoo/entity/TimeStamp.java, src/main/java/com/example/beepoo/repository/ItemRepository.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 등록 및 상세조회 기능 개발

src/main/java/com/example/beepoo/BeepooApplication.java, src/main/java/com/example/beepoo/controller/DepartmentController.java, src/main/java/com/example/beepoo/controller/TestController.java, src/main/java/com/example/beepoo/dto/DepartmentRequestDto.java, src/main/java/com/example/beepoo/dto/DepartmentResponseDto.java, src/main/java/com/example/beepoo/dto/GlobalResponseDto.java, src/main/java/com/example/beepoo/entity/Department.java, src/main/java/com/example/beepoo/entity/TimeStamp.java, src/main/java/com/example/beepoo/entity/User.java, src/main/java/com/example/beepoo/exception/CustomException.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/DepartmentRepository.java, src/main/java/com/example/beepoo/repository/UserRepository.java, src/main/java/com/example/beepoo/service/DepartmentService.java
=> feat:부서등록기능 구현

build.gradle, src/main/java/com/example/beepoo/QueryDslConfig.java, src/main/java/com/example/beepoo/TomcatWebCustomConfig.java, src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/dto/ItemDto.java, src/main/java/com/example/beepoo/dto/ItemSearchCondition.java, src/main/java/com/example/beepoo/entity/ItemEntity.java, src/main/java/com/example/beepoo/exception/CustomException.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/ItemCustomRepository.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/service/DepartmentService.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 목록 조회 기능 개발

src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/dto/ItemRequestDto.java, src/main/java/com/example/beepoo/dto/ItemResponseDto.java, src/main/java/com/example/beepoo/entity/Item.java, src/main/java/com/example/beepoo/repository/ItemCustomRepository.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemRepository.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 수정 기능 개발

src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/repository/ItemCustomRepository.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 삭제 기능 개발

.gitignore, src/main/java/com/example/beepoo/controller/DepartmentController.java, src/main/java/com/example/beepoo/entity/Department.java, src/main/java/com/example/beepoo/entity/User.java, src/main/java/com/example/beepoo/exception/CustomException.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/DepartmentRepository.java, src/main/java/com/example/beepoo/repository/UserRepository.java, src/main/java/com/example/beepoo/service/DepartmentService.java
=> feat: 사원 등록, 수정,삭제,조회 기능 구현

src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/dto/DepartmentResponseDto.java, src/main/java/com/example/beepoo/repository/AskRepository.java, src/main/java/com/example/beepoo/service/AskService.java, src/main/java/com/example/beepoo/service/DepartmentService.java
=> feat: 대시보드 api 개발

build.gradle, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/dto/UserRequestDto.java, src/main/java/com/example/beepoo/exception/CustomExceptionHandler.java, src/main/java/com/example/beepoo/exception/ErrorResponseEntity.java, src/main/java/com/example/beepoo/service/UserService.java
=> feat: validation 기능 구현

src/main/java/com/example/beepoo/entity/Department.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/util/OrderByNull.java
=> fix: 요청 조회 오류 수정 (날짜 검색, 정렬, 무한 재귀)

src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/controller/DepartmentController.java, src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/repository/ItemRepository.java, src/main/java/com/example/beepoo/service/DepartmentService.java, src/main/java/com/example/beepoo/service/ItemService.java, src/main/java/com/example/beepoo/service/UserService.java
=> feat: 비품, 부서, 유저 중복 체크 기능 추가

.prettierrc, src/main/java/com/example/beepoo/dto/ItemRequestDto.java, src/main/java/com/example/beepoo/dto/ItemResponseDto.java, src/main/java/com/example/beepoo/entity/Ask.java, src/main/java/com/example/beepoo/entity/Item.java, src/main/java/com/example/beepoo/enums/ItemStatusEnum.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemRepository.java, src/main/java/com/example/beepoo/service/AskService.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 요청 시, 비품 상태 확인

build.gradle, src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/dto/UserRequestDto.java, src/main/java/com/example/beepoo/dto/UserResponseDto.java, src/main/java/com/example/beepoo/entity/User.java, src/main/java/com/example/beepoo/service/UserService.java
=> feat: jwt 및 security 설정

src/main/java/com/example/beepoo/config/WebSecurityConfig.java, src/main/java/com/example/beepoo/controller/TestController.java, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/jwt/JwtUtil.java, src/main/java/com/example/beepoo/repository/UserRepository.java, src/main/java/com/example/beepoo/service/DepartmentService.java, src/main/java/com/example/beepoo/service/UserService.java
=> feat: jwt 및 security 설정 3

.prettierrc, src/main/java/com/example/beepoo/dto/AskRequestDto.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java
=> feat: 요청 목록 조회 시, 비품명/요청자/처리자 검색 옵션 추가

src/main/java/com/example/beepoo/DbInit.java, src/main/java/com/example/beepoo/repository/UserRepository.java
=> feat: 초기 admin 계정 추가

src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/dto/AskRequestDto.java, src/main/java/com/example/beepoo/entity/Ask.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/service/AskService.java, src/main/java/com/example/beepoo/util/CurrentUser.java
=> feat: 요청자, 처리자 추가

src/main/java/com/example/beepoo/controller/DepartmentController.java, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java, src/main/java/com/example/beepoo/dto/PasswordRequestDto.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/DepartmentRepository.java, src/main/java/com/example/beepoo/service/DepartmentService.java, src/main/java/com/example/beepoo/service/UserService.java, src/main/java/com/example/beepoo/util/CustomUtil.java
=> feat: 권한 확인 기능 추가

build.gradle, src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/controller/DepartmentController.java, src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java, src/main/java/com/example/beepoo/dto/DepartmentRequestDto.java, src/main/java/com/example/beepoo/dto/LoginRequestDto.java, src/main/java/com/example/beepoo/dto/PasswordRequestDto.java, src/main/java/com/example/beepoo/dto/UserRequestDto.java, src/main/java/com/example/beepoo/service/UserService.java
=> feat: swagger 적용

src/main/java/com/example/beepoo/config/WebConfig.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java
=> chore: CORS 설정

src/main/java/com/example/beepoo/controller/UserController.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java, src/main/java/com/example/beepoo/dto/AskResponseDto.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java
=> feat: 요청 현황 조회 응답 변경

src/main/java/com/example/beepoo/config/OpenApiConfig.java, src/main/java/com/example/beepoo/config/WebSecurityConfig.java, src/main/java/com/example/beepoo/customFilter/AuthFilter.java, src/main/java/com/example/beepoo/jwt/JwtUtil.java, src/main/java/com/example/beepoo/service/UserService.java, src/main/java/com/example/beepoo/util/CurrentUser.java
=> fix: token header 로 발급

src/main/java/com/example/beepoo/controller/ItemController.java, src/main/java/com/example/beepoo/dto/AskResponseDto.java, src/main/java/com/example/beepoo/dto/ItemRequestDto.java, src/main/java/com/example/beepoo/dto/ItemResponseDto.java, src/main/java/com/example/beepoo/dto/ItemTypeRequestDto.java, src/main/java/com/example/beepoo/entity/Item.java, src/main/java/com/example/beepoo/entity/ItemType.java, src/main/java/com/example/beepoo/entity/TimeStamp.java, src/main/java/com/example/beepoo/exception/ErrorCode.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemTypeRepository.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 타입 등록 기능 구현

src/main/java/com/example/beepoo/dto/AskResponseDto.java, src/main/java/com/example/beepoo/dto/ItemResponseDto.java, src/main/java/com/example/beepoo/entity/Item.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemRepository.java, src/main/java/com/example/beepoo/service/AskService.java
=> feat: 비품 목록 조회 응답 변경

src/main/java/com/example/beepoo/dto/AskRequestDto.java, src/main/java/com/example/beepoo/dto/AskResponseDto.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java
=> feat: 요청 현황 조회 시, 비품 종류 검색 추가

src/main/java/com/example/beepoo/dto/ItemResponseDto.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemTypeRepository.java
=> feat: 비품 조회 시, 비품 종류 표시

src/main/java/com/example/beepoo/controller/AskController.java, src/main/java/com/example/beepoo/enums/AskTypeEnum.java, src/main/java/com/example/beepoo/enums/ItemStatusEnum.java, src/main/java/com/example/beepoo/service/AskService.java
=> feat: 요청 상태 조회 기능 추가

src/main/java/com/example/beepoo/dto/GlobalResponseDto.java, src/main/java/com/example/beepoo/repository/AskCustomRepository.java, src/main/java/com/example/beepoo/repository/AskCustomRepositoryImpl.java, src/main/java/com/example/beepoo/repository/ItemCustomRepository.java, src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java, src/main/java/com/example/beepoo/service/AskService.java, src/main/java/com/example/beepoo/service/ItemService.java
=> feat: 비품 목록 조회, 요청 현황 조회 totalCnt 추가

src/main/java/com/example/beepoo/repository/ItemCustomRepositoryImpl.java
=> fix: 비품 목록 조회 시, 날짜 포맷 오류 수정
